### ISSUE TITLE
Implications of MH_FREEZE_METHOD_NONE_UNSAFE

### ISSUE THREAD

**Issue by p0358** [m417z/minhook#3]
```cpp
    // Threads are not suspended and instruction pointer registers are not
    // adjusted. Don't use this method unless you understand the implications
    // and know that it's safe.
    MH_FREEZE_METHOD_NONE_UNSAFE
```

Can you elaborate a bit on the implications of this?

If we apply the hooks in a program at a stage on which we are sure nothing will call any code that's about to be hooked, can it simply be considered fully safe then?

**Comment by m417z** [comment]
Yes, as long as you're sure no thread is in the middle of calling the target functions and no thread will be calling them until hooking is completed, `MH_FREEZE_METHOD_NONE_UNSAFE` should be safe.
